service: serverless456
custom: 
  serverless-offline:
    httpPort: 4004
    websocketPort: 4005
    lambdaPort: 4006

plugins:
  - serverless-offline

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x


functions:
  hello12:                                      ### npx serverless invoke local --function hello12
    handler: handler22.hello
  
  hello13:                                      ### npx serverless invoke local --function hello13
    handler: handler22.football24

  practice23:                                   ### invoked by Http event --- then, sls listens on httpPort 4004.
    handler: handler23.main                     ### without events property... sls listens on lambdaPort 4006                     
    timeout: 30                                 ### npx serverless invoke local --function practice23
    events:
      - http:
          path: 'cric/{proxy+}'                 ### npx .. --data '{ "queryStringParameters": {"id":"dhoni thala"}}'
          method: any
      - http:
           path: 'fb/{proxy+}'
           method: any

  graphql23:                                    ### npx serverless invoke local -f graphql23 -p handler25_query1.json
    handler: handler25.graphql_handler
    timeout: 900
    memorySize: 2048
    events:
      - httpApi: 
           path: /graphql
           method: any