service: serverless456
custom: 
  serverless-offline:
    httpPort: 4004
    websocketPort: 4005
    lambdaPort: 4006

plugins:
  - serverless-offline

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x


functions:
  hello12:                                    # invoked locally
    handler: handler22.hello                      # 
  
  hello13:
    handler: handler22.football24

  hello14:        #### ignore this
    handler: handler24.api23
    events:
      - http:
          path: '/hello14/{proxy+}'
          method: any

  practice22:                                 # invoked by Http event
    handler: handler23.main                     # then, sls listens on httpPort 4004.
    timeout: 30                                 # without events property... sls listens on lambdaPort 4006
    events:
      - http:
          path: '{proxy+}'
          method: any